# Generated by Django 2.0.3 on 2018-03-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device_Manageable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('sbsbm_manageable', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='device_upkeep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_up', models.CharField(max_length=200)),
                ('sbsbm_up', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='upkeep_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('upk_id', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('uname', models.CharField(max_length=100)),
                ('permission', models.IntegerField(default=0)),
            ],
        ),
    ]
