# Generated by Django 2.0.3 on 2018-03-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device',
            field=models.IntegerField(choices=[(0, '全国'), (1, '省、直辖市'), (2, '市、直辖市区'), (3, '区、县等')], default='1', verbose_name='物业'),
        ),
    ]
