# Generated by Django 2.0.3 on 2018-03-30 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_device_last_date_mainten'),
    ]

    operations = [
        migrations.DeleteModel(
            name='device',
        ),
    ]
