# Generated by Django 2.0.3 on 2018-03-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SBSBM', models.CharField(max_length=255)),
                ('SBZCDM', models.CharField(max_length=255)),
                ('DTAZDZ', models.CharField(max_length=255)),
                ('WBDWMC', models.CharField(max_length=255)),
                ('SYDW', models.CharField(max_length=255)),
                ('SYDWNBBH', models.CharField(max_length=255)),
                ('DTJYJG', models.CharField(max_length=255)),
                ('ZJJYRQ', models.CharField(max_length=255)),
                ('ZJWBRQ', models.CharField(max_length=255)),
            ],
        ),
    ]
