# Generated by Django 2.0.3 on 2018-03-31 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180331_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='upkepp',
            new_name='upkeep',
        ),
    ]
