# Generated by Django 2.0.3 on 2018-03-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180331_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device',
        ),
        migrations.AddField(
            model_name='user',
            name='device',
            field=models.ManyToManyField(default='1', max_length=255, to='users.device', verbose_name='物业'),
        ),
    ]
