# Generated by Django 2.0.3 on 2018-04-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180401_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cookie',
            field=models.CharField(default='', max_length=100, verbose_name='用户认证标识'),
        ),
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(default='default', max_length=100, verbose_name='用户标识'),
        ),
    ]
