# Generated by Django 2.0.3 on 2018-04-01 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180401_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='日志创建时间')),
                ('type', models.CharField(choices=[('0', '添加设备'), ('1', '删除设备'), ('2', '修改设备')], max_length=15, verbose_name='日志类型')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='freq',
            field=models.IntegerField(default=0, verbose_name='使用频率'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_active_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最近操作时间'),
        ),
        migrations.AddField(
            model_name='log',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.device', verbose_name='操作设备'),
        ),
        migrations.AddField(
            model_name='log',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='日志所属人'),
        ),
    ]
