# Generated by Django 2.0.3 on 2018-04-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20180416_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='freq',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_unix_time',
            field=models.BigIntegerField(default=0, verbose_name='最后操作时间'),
        ),
    ]
