# Generated by Django 2.0.3 on 2018-03-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180331_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device',
            field=models.CharField(max_length=255, verbose_name='物业'),
        ),
        migrations.AlterField(
            model_name='user',
            name='upkeep',
            field=models.CharField(max_length=255),
        ),
    ]
