# Generated by Django 2.0.3 on 2018-04-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20180416_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='freq',
            field=models.IntegerField(default=0, max_length=40),
        ),
    ]
