# Generated by Django 2.0.3 on 2018-03-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180331_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upkepp',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='device',
            field=models.IntegerField(default='1', verbose_name='物业'),
        ),
    ]
