# Generated by Django 2.0.3 on 2018-03-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180331_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device',
            field=models.CharField(default='', max_length=255, verbose_name='物业'),
        ),
    ]
