# Generated by Django 2.0.3 on 2018-03-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180331_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='DTAZDZ',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='DTJYJG',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='SBSBM',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='SBZCDM',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='SYDW',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='SYDWNBBH',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='WBDWMC',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='ZJJYRQ',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='ZJWBRQ',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='device',
            field=models.CharField(default='1', max_length=255, verbose_name='物业'),
        ),
        migrations.AlterField(
            model_name='user',
            name='upkeep',
            field=models.CharField(default='', max_length=255),
        ),
    ]
