# Generated by Django 2.0.3 on 2018-03-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180331_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device',
        ),
        migrations.AddField(
            model_name='user',
            name='device',
            field=models.CharField(default='1', max_length=255, verbose_name='物业'),
        ),
    ]
