# Generated by Django 2.0.3 on 2018-04-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180401_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_rights',
            field=models.CharField(choices=[('0', '超级管理员'), ('1', '物业管理员'), ('2', '普通用户')], default='', max_length=15, verbose_name='用户权限'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='white_list',
            field=models.CharField(default='', max_length=1000, verbose_name='电话白名单'),
        ),
    ]
