# Generated by Django 2.0.3 on 2018-04-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180410_0703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='white_list',
        ),
        migrations.AddField(
            model_name='user',
            name='white_list',
            field=models.CharField(default='', max_length=1000, verbose_name='电话白名单'),
        ),
    ]
